### ISSUE TITLE
Please make the README more attractive 

### ISSUE THREAD

**Issue by wiredfoxterrier** [wiredfoxterrier/FirstMLProject#1]
Please make the README file a little more attractive. This repository is for Text Recognition and will be coded using Python3. 

If you contribute to this repository please add your name on the contributor file.

Thanks,
Ansh Sharma
(wiredfoxterrier)

**Comment by VARhimank** [comment]
@wiredfoxterrier please assign this to me

**Comment by wiredfoxterrier** [comment]
@VARhimank you are assigned to this issue

**Comment by chandankumar1307** [comment]
Hello Bro...Please assign me the issue and you will never regret it.

**Comment by wiredfoxterrier** [comment]
@chandankumar1307 you have also been assigned to this issue

**Comment by karankeyash** [comment]
@wiredfoxterrier can you please add `hacktoberfest` in the topic of the repo? I got this error after the commit.

```
Ineligible Repository
Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate.
```

**Comment by karankeyash** [comment]
@wiredfoxterrier thank you, it is reflecting now....

**Comment by wiredfoxterrier** [comment]
@karankeyash I have added it as the topic to this repo. I believe future PRs could count towards Hacktoberfest. I am unsure if they will review the one you have already submitted.

**Comment by karankeyash** [comment]
Yes, the PR is counting now.
________________________________

**Comment by wiredfoxterrier** [comment]
@VARhimank @chandankumar1307 @karankeyash It would be great if you could submit a PR with DATA as well as. The Data could be written or printed or any other form of English Text. There is no assignment for this but please put the data in the database folder. 

Thanks,
Ansh Sharma
(wiredfoxterrier)
